/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e63e71b156538a04f57b2d4daa0d319)
interface __BaseEnv_Env {
	AUTH_REQUIRED: "true";
	MEDIA_PLANE_ENABLED: "true";
	PUBLIC_ROOMS_ENABLED: "true";
	IDENTITY_PROVIDER: "supabase";
	SESSION_ISSUER: "stix-magic-vc-node";
	STUN_URLS: "stun:stun.l.google.com:19302";
	LOG_LEVEL: "info";
	ASHY_UNIT: DurableObjectNamespace<import("./workers/ashy-unit").AshyUnit>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/ashy-unit");
		durableNamespaces: "AshyUnit";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_REQUIRED" | "MEDIA_PLANE_ENABLED" | "PUBLIC_ROOMS_ENABLED" | "IDENTITY_PROVIDER" | "SESSION_ISSUER" | "STUN_URLS" | "LOG_LEVEL">> {}
}
